output "smtp_host" {
  description = "OCI Email Delivery SMTP host for this region"
  value       = "smtp.email.${var.region}.oci.oraclecloud.com"
}

output "smtp_username" {
  description = "SMTP username (auto-generated by OCI)"
  value       = oci_identity_smtp_credential.main.username
  sensitive   = true
}

output "smtp_password" {
  description = "SMTP password (auto-generated by OCI)"
  value       = oci_identity_smtp_credential.main.password
  sensitive   = true
}

output "approved_sender_email" {
  description = "Approved From-address for OCI Email Delivery"
  value       = oci_email_sender.noreply.email_address
}

output "dkim_cname_records" {
  description = "CNAME records to create at your DNS registrar to enable DKIM signing"
  value = {
    name  = oci_email_dkim.main.dns_subdomain_name
    value = oci_email_dkim.main.cname_record_value
  }
}
